name: tradelog_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:

  # Core
  collection: ^1.19.0

  # Network
  dio: ^5.5.0+1

  # Serverpod
  serverpod: ^2.1.5
  serverpod_auth_server: ^2.1.5
  serverpod_cloud_storage_s3: ^2.1.5

  # Redis Queue
  synchronized: ^3.1.0+1

  # Monitoring
  sentry: ^8.9.0

dev_dependencies:
  lints: '>=3.0.0 <5.0.0'
